name: JackSpawner
version: ${version}
main: com.github.jackspawner.JackSpawnerPlugin
api-version: '1.21'
author: JackSpawner Developer
description: Плагин добавляет Кирку Джека для добычи спавнеров

commands:
  givejack:
    description: Выдаёт Кирку Джека
    usage: /<command>
    permission: jackspawner.give
  jackshop:
    description: Открывает магазин Кирки Джека
    usage: /jackshop

permissions:
  jackspawner.give:
    description: Разрешение на получение Кирки Джека
    default: op