#!/bin/bash

# Информация о проекте
BRANCH_NAME="878101107559362"
PROJECT_NAME="JackSpawner"
JAR_FILE="JackSpawner-1.0.0.jar"
ARCHIVE_FILE="JackSpawner-878101107559362.tar.gz"

echo "=================================================="
echo "🎉 ПРОЕКТ JACKSPAWNER ГОТОВ К ПУБЛИКАЦИИ!"
echo "=================================================="
echo ""
echo "📋 ИНФОРМАЦИЯ О ПРОЕКТЕ:"
echo "------------------------"
echo "📦 Название: $PROJECT_NAME"
echo "🌿 Ветка: $BRANCH_NAME"
echo "📁 Архив: $ARCHIVE_FILE"
echo "💾 JAR файл: $JAR_FILE"
echo ""
echo "📂 ФАЙЛЫ ПРОЕКТА:"
echo "-----------------"
ls -lh *.jar *.tar.gz 2>/dev/null | awk '{print "  • "$9" ("$5")"}'
echo ""
echo "🔧 СТРУКТУРА КОДА:"
echo "------------------"
echo "  • src/main/java/         - Исходный код Java"
echo "  • src/main/resources/    - Ресурсы (plugin.yml)"
echo "  • build.gradle.kts       - Конфигурация Gradle"
echo "  • README.md              - Документация"
echo ""
echo "📥 СПОСОБЫ ПУБЛИКАЦИИ:"
echo "----------------------"
echo ""
echo "1️⃣  ВАРИАНТ 1: Загрузка на файлообменник"
echo "   • Используйте файл: $ARCHIVE_FILE"
echo "   • Рекомендуемые сервисы:"
echo "     - file.io"
echo "     - transfer.sh"
echo "     - WeTransfer"
echo ""
echo "2️⃣  ВАРИАНТ 2: Создание GitHub репозитория"
echo "   • Создайте новый репозиторий на github.com"
echo "   • Выполните команды:"
echo "     git remote add origin https://github.com/YOUR_USERNAME/$PROJECT_NAME.git"
echo "     git push -u origin $BRANCH_NAME"
echo ""
echo "3️⃣  ВАРИАНТ 3: Прямое использование"
echo "   • Готовый JAR: $JAR_FILE"
echo "   • Поместите в папку plugins/ сервера Paper 1.21.8"
echo ""
echo "⚙️  ТЕХНИЧЕСКИЕ ДЕТАЛИ:"
echo "----------------------"
echo "  • Версия: 1.0.0"
echo "  • Paper API: 1.21-R0.1-SNAPSHOT"
echo "  • Java: 21+"
echo "  • Сборка: Gradle 8.5"
echo ""
echo "🎮 КОМАНДЫ ПЛАГИНА:"
echo "------------------"
echo "  • /givejack - Получить Кирку Джека (права: jackspawner.give)"
echo ""
echo "✅ Плагин полностью готов к использованию!"
echo "=================================================="